FROM python:3.8.3-alpine

# set work directory
WORKDIR /mnt/d/CONTAINER/ProjectArk

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip 
COPY ./requirements.txt /mnt/d/CONTAINER/ProjectArk
RUN pip install -r requirements.txt

# copy project
COPY . /mnt/d/CONTAINER/ProjectArk

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]